name: Deploy Bidder Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t hunais/bidder-backend .
      - name: Push to docker image
        run: docker push hunais/bidder-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pulling image
        run: docker pull hunais/bidder-backend:latest
      - name: Stop existing container
        run: docker stop bidder-backend || true
      - name: Deleting existing container
        run: docker rm bidder-backend || true
      - name: Run docker container
        run: |
          docker run -d -p 5000:5000 --name bidder-backend \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e CLIENT_ORIGIN="${{ secrets.CLIENT_ORIGIN }}" \
            -e EMAIL="${{ secrets.EMAIL }}" \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e MAIL_LINK="${{ secrets.MAIL_LINK }}" \
            -e STRIPE_API_KEY="${{ secrets.STRIPE_API_KEY }}" \
            -e MODE="${{ secrets.MODE }}" \
            hunais/bidder-backend:latest